#!/bin/sh /etc/rc.common
# /etc/init.d/ghost-node

START=25
STOP=30

### BEGIN INIT INFO
# Provides:          node
# Required-Start:    $network
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Ghost Node interface
# Description:       Startup script for starting the node script responsible for the frontend representation of Ghost
### END INIT INFO

APPLICATION_PATH="/www/ghost/start"
SCREEN_NAME="ghost-node"
WATCH_DIR="/www/ghost"

start() {
    screen -S $SCREEN_NAME -d -m sh -c "supervisor -w $WATCH_DIR $APPLICATION_PATH"
    echo "Server started on screen $SCREEN_NAME"
}
stop() {
    screen -X -S $SCREEN_NAME quit
    echo "Server $SCREEN_NAME shutting down"
}
restart() {
    screen -X -S $SCREEN_NAME quit
    screen -S $SCREEN_NAME -d -m sh -c "supervisor -w $WATCH_DIR $APPLICATION_PATH"
    echo "Server $SCREEN_NAME restarting"
}