language: c
compiler:
  - gcc
  - clang
script: make config && make && make test && ./sslsplit -V
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl-dev libevent-dev check
